[package]
name = "authenticator"
version = "0.2.3"
edition = "2021"
license = "Apache-2.0"

[dependencies]
clap = { version = "3.2.12", features = ["derive"] }
totp-rs = "2.0.1"
base32 = "0.4.0"
sodiumoxide = "0.2.7"
base64 = "0.13.0"
rpassword = "7.0.0"
